### PR TITLE
Add GH Action to check for changes in createSite.php that may need changes in docker

### PR DESCRIPTION
**Pull request by kylemhall**
This action attempts to do basic checking of changes to createSite.php that would need changes to Docker files, and then checks to see if any files in the docker directory have been changes. I'm sure we can improve this check with experience.

Closes Aspen-Discovery/aspen-discovery#2026

### CODE REVIEW

**Comment by kylemhall** [comment]
@lucasmontoya13 can you have a look at this and let me know if there is any way we can improve it?

**Comment by kylemhall** [comment]
Tests:
Failure! https://github.com/kylemhall/aspen-discovery/actions/runs/10565908295/job/29271451099
Success! https://github.com/kylemhall/aspen-discovery/actions/runs/10566183988/job/29272363017

**Comment by lucasmontoya13** [comment]
This PR looks very good! I think i could polish this a little bit more. I will make more tests to corroborate it. Thank you

**Comment by mdnoble73** [comment]
Why check for just Aspen or Koha? What we probably want to do to see if new logic may need to go into Docker is check for changes to the createSiteTemplate.ini since that is where new variables would be added.

**Comment by kylemhall** [comment]
> Why check for just Aspen or Koha? What we probably want to do to see if new logic may need to go into Docker is check for changes to the createSiteTemplate.ini since that is where new variables would be added.

That is a really good point @mdnoble73! I had the adb/ktd integration stuck in my head. I'll amend the pull request.

**Comment by mdnoble73** [comment]
The commit message and testing notes for this are no longer accurate, can you please update with the actual changes? Also I think rather than targeting createSite.php, this should target  createSiteTemplate.ini which would indicate new variables being added or existing variables being needed which the docker scripts may or may not need to respond to.

**Comment by kylemhall** [comment]
> The commit message and testing notes for this are no longer accurate, can you please update with the actual changes? Also I think rather than targeting createSite.php, this should target createSiteTemplate.ini which would indicate new variables being added or existing variables being needed which the docker scripts may or may not need to respond to.

Sounds good! I'll get the patch set amended asap!

**Comment by kylemhall** [comment]
Failure! https://github.com/kylemhall/aspen-discovery/actions/runs/10687602144/job/29625572342
Success! https://github.com/kylemhall/aspen-discovery/actions/runs/10687671062/job/29625785651

**Review by mdnoble73 — APPROVED** [review]

**Pull request merged**
