### PR TITLE
DIS-42 Switch from hard to soft commit for Solr during full reindexing

### PR DESCRIPTION
**Pull request by kylemhall**
We are seeing lots of errors like this:

[main] ERROR 11/01 03:55:04,356 - Error adding grouped work to solr 2dff117f-8866-0ca0-d107-1630f2f3d512-eng quitting java.io.IOException: Request processing has stalled for 15013ms with 25 remaining elements in the queue. at org.apache.solr.client.solrj.impl.ConcurrentUpdateHttp2SolrClient.request(ConcurrentUpdateHttp2SolrClient.java:449) ~[solr-solrj-8.11.2.jar:8.11.2 17dee71932c683e345508113523e764c3e4c80fa - mdrob - 2022-06-13 11:27:56] at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:214) ~[solr-solrj-8.11.2.jar:8.11.2 17dee71932c683e345508113523e764c3e4c80fa - mdrob - 2022-06-13 11:27:56] at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:177) ~[solr-solrj-8.11.2.jar:8.11.2 17dee71932c683e345508113523e764c3e4c80fa - mdrob - 2022-06-13 11:27:56] at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:138) ~[solr-solrj-8.11.2.jar:8.11.2 17dee71932c683e345508113523e764c3e4c80fa - mdrob - 2022-06-13 11:27:56] at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:156) ~[solr-solrj-8.11.2.jar:8.11.2 17dee71932c683e345508113523e764c3e4c80fa - mdrob - 2022-06-13 11:27:56] at org.aspen_discovery.reindexer.GroupedWorkIndexer.processGroupedWork(GroupedWorkIndexer.java:1180) [reindexer.jar:?] at org.aspen_discovery.reindexer.GroupedWorkIndexer.processGroupedWork(GroupedWorkIndexer.java:1005) [reindexer.jar:?] at org.aspen_discovery.reindexer.GroupedWorkIndexer.processGroupedWorks(GroupedWorkIndexer.java:887) [reindexer.jar:?] at org.aspen_discovery.reindexer.GroupedReindexMain.main(GroupedReindexMain.java:139) [reindexer.jar:?]

These errors cause the grouped work indexer to crash.

A Solr expert has explained that the hard commits here are forcing a constant and continuous reloading of data as each record is committed. The recommendation is to switch to soft commits and not enable waitFlush or waitSearcher. AFACT this is the only commit that disables soft commits for solr.

### CODE REVIEW

**Comment by mdnoble73** [comment]
The change you made is only for the very last call at the very end of indexing, not after each record is committed which does not sound like a root cause for what you are describing.

**Comment by kylemhall** [comment]
> The change you made is only for the very last call at the very end of indexing, not after each record is committed which does not sound like a root cause for what you are describing.

Do you have any thoughts on where the hard commit is being triggered?
Have a look at https://aspen-discovery.atlassian.net/browse/DIS-43

There are a good number of solr commits that are hard commits, but not in the reindexer. I'm trying to correlate the logs to the code without any context to go on. It may very well be that a different exporter is causing the hard commit but the reindexer is crashing because of that commit. Perhaps we need to make this change for all hard commits in the code.

**Comment by mdnoble73** [comment]
If you need consulting help, we'd be happy to help. For now can you please mark this as a draft if it isn't ready to be merged? Also please make sure to add a test plan and release notes.

**Comment by kylemhall** [comment]
> If you need consulting help, we'd be happy to help. For now can you please mark this as a draft if it isn't ready to be merged? Also please make sure to add a test plan and release notes.

No worries! I'm excited to learn 😁 
I also think this is still a good pull request, as there is no reason to perform a hard commit here, it can still cause problems. If you'd rather wait in case more commit calls need updated that's fine by me!

**Comment by mdnoble73** [comment]
You still need release notes and a test plan. Also since you aren't sure what it will do this will need to be submitted against 24.12 rather than 24.11.

**Pull request closed without merging**
